// <auto-generated />
using System;
using EventService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EventService.Infrastructure.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260409163731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventService.Core.Models.Billet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilletTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("VisiteurId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("BilletTypeId");

                    b.HasIndex("VisiteurId");

                    b.ToTable("Billets");
                });

            modelBuilder.Entity("EventService.Core.Models.BilletType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EvenementId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Sold")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.ToTable("BilletTypes");
                });

            modelBuilder.Entity("EventService.Core.Models.Evenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Disponibilite")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LienPartage")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("LocalisationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("OrganisateurId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PlacesRestantes")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TypeEvent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LocalisationId");

                    b.HasIndex("OrganisateurId");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("EventService.Core.Models.Localisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Localisations");
                });

            modelBuilder.Entity("EventService.Core.Models.Organisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Verifie")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("Id");

                    b.ToTable("Organisateurs");
                });

            modelBuilder.Entity("EventService.Core.Models.Visiteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Visiteurs");
                });

            modelBuilder.Entity("Favoris", b =>
                {
                    b.Property<int>("EvenementId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VisiteurId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EvenementId", "VisiteurId");

                    b.HasIndex("VisiteurId");

                    b.ToTable("Favoris");
                });

            modelBuilder.Entity("EventService.Core.Models.Billet", b =>
                {
                    b.HasOne("EventService.Core.Models.BilletType", "BilletType")
                        .WithMany("Billets")
                        .HasForeignKey("BilletTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventService.Core.Models.Visiteur", "Visiteur")
                        .WithMany("Billets")
                        .HasForeignKey("VisiteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BilletType");

                    b.Navigation("Visiteur");
                });

            modelBuilder.Entity("EventService.Core.Models.BilletType", b =>
                {
                    b.HasOne("EventService.Core.Models.Evenement", "Evenement")
                        .WithMany("BilletTypes")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("EventService.Core.Models.Evenement", b =>
                {
                    b.HasOne("EventService.Core.Models.Localisation", "Localisation")
                        .WithMany("Evenements")
                        .HasForeignKey("LocalisationId");

                    b.HasOne("EventService.Core.Models.Organisateur", "Organisateur")
                        .WithMany("Evenements")
                        .HasForeignKey("OrganisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localisation");

                    b.Navigation("Organisateur");
                });

            modelBuilder.Entity("Favoris", b =>
                {
                    b.HasOne("EventService.Core.Models.Evenement", null)
                        .WithMany()
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventService.Core.Models.Visiteur", null)
                        .WithMany()
                        .HasForeignKey("VisiteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventService.Core.Models.BilletType", b =>
                {
                    b.Navigation("Billets");
                });

            modelBuilder.Entity("EventService.Core.Models.Evenement", b =>
                {
                    b.Navigation("BilletTypes");
                });

            modelBuilder.Entity("EventService.Core.Models.Localisation", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("EventService.Core.Models.Organisateur", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("EventService.Core.Models.Visiteur", b =>
                {
                    b.Navigation("Billets");
                });
#pragma warning restore 612, 618
        }
    }
}
