// <auto-generated />
using System;
using EventService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EventService.Infrastructure.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260427131532_MakePaymentTransactionIdNullable")]
    partial class MakePaymentTransactionIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventService.Core.Models.Billet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilletTypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BILLET_TYPE_ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<DateTime?>("DateReservation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_RESERVATION");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_VALIDATION");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PAYMENT_TRANSACTION_ID");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("Disponible")
                        .HasColumnName("STATUT");

                    b.Property<int?>("VisiteurId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VISITEUR_ID");

                    b.HasKey("Id");

                    b.HasIndex("BilletTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BILLETS", (string)null);
                });

            modelBuilder.Entity("EventService.Core.Models.BilletType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvenementId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EVENEMENT_ID");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("PRIX");

                    b.Property<int>("Quantite")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITE");

                    b.Property<int>("Vendu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("VENDU");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.ToTable("BILLET_TYPES", (string)null);
                });

            modelBuilder.Entity("EventService.Core.Models.Evenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacite")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPACITE");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORIE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Disponibilite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DISPONIBILITE");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("END_DATE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_DELETED");

                    b.Property<string>("LienPartage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("LIEN_PARTAGE");

                    b.Property<int?>("LocalisationId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LOCALISATION_ID");

                    b.Property<int>("OrganisateurId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORGANISATEUR_ID");

                    b.Property<int>("PlacesRestantes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLACES_RESTANTES");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITRE");

                    b.Property<string>("TypeEvent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TYPE_EVENT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("LocalisationId");

                    b.ToTable("EVENEMENTS", (string)null);
                });

            modelBuilder.Entity("EventService.Core.Models.Localisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ADRESSE");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CODE_POSTAL");

                    b.Property<double?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("VILLE");

                    b.HasKey("Id");

                    b.ToTable("LOCALISATIONS", (string)null);
                });

            modelBuilder.Entity("EventService.Core.Models.Billet", b =>
                {
                    b.HasOne("EventService.Core.Models.BilletType", "BilletType")
                        .WithMany("Billets")
                        .HasForeignKey("BilletTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BilletType");
                });

            modelBuilder.Entity("EventService.Core.Models.BilletType", b =>
                {
                    b.HasOne("EventService.Core.Models.Evenement", "Evenement")
                        .WithMany("BilletTypes")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("EventService.Core.Models.Evenement", b =>
                {
                    b.HasOne("EventService.Core.Models.Localisation", "Localisation")
                        .WithMany("Evenements")
                        .HasForeignKey("LocalisationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("EventService.Core.Models.BilletType", b =>
                {
                    b.Navigation("Billets");
                });

            modelBuilder.Entity("EventService.Core.Models.Evenement", b =>
                {
                    b.Navigation("BilletTypes");
                });

            modelBuilder.Entity("EventService.Core.Models.Localisation", b =>
                {
                    b.Navigation("Evenements");
                });
#pragma warning restore 612, 618
        }
    }
}
